### ISSUE TITLE
secret_ide/_data, flags: 0x1000: no such file or directory

### ISSUE THREAD

**Issue by luca992** [digiline-io/Secret-IDE-Plugin#4] opened 2022-09-25 17:30 UTC
I tried the three setup commands listed in the read me. And I get this error:

```
lucaspinazzola@Lucas-MBP ~ % docker volume create --driver local --opt type=none --opt device=${PWD}/data --opt o=bind secret_ide
secret_ide
lucaspinazzola@Lucas-MBP ~ % docker run -p 8888:8888 -v secret_ide:/home/secret-ide-user/ -it ghcr.io/digiline-io/secret-ide:latest
docker: Error response from daemon: failed to mount local volume: mount /host_mnt/Users/lucaspinazzola/data:/var/lib/docker/volumes/secret_ide/_data, flags: 0x1000: no such file or directory.
See 'docker run --help'.
```

I'm on a m1 mac, is arm64 not supported? Or is this just a normal path issue?

**Comment by dannym-arx** [comment] 2022-09-25 20:49
M1 is supported actually, can you try doing `mkdir data` after creating the volume?

**Comment by luca992** [comment] 2022-09-28 19:39
> M1 is supported actually, can you try doing `mkdir data` after creating the volume?

ahh you're right. the `/host_mnt/` path prefix in the error was confusing me. running `mkdir ~/data` worked.

might want to add that to the readme

**Comment by dannym-arx** [comment] 2022-09-28 21:07
awesome, I'm glad the issue is fixed, closing :+1:

**Closed as completed by dannym-arx** 2022-09-28 21:07 UTC
